const systemUserMasterPwd = "1234";
const consortiumUserMasterPwd = "1234";

module.exports = {

    APP_SORT_ORDER_ASC : 'ASC',
    APP_SORT_ORDER_DSC : 'DSC',

    DEFAULT_CURRENCY_PREFIX : 'Rs. ',
    DEFAULT_CURRENCY_CODE : 'Rs',
    DEFAULT_CURRENCY_TEXT : 'Rupees',

    MAT_COLUMN_NAME_STATUS : 'status',

    FORMULATED_HIERARCH_NAME_STRING_SEP: ' > ',

    PARAM_SKIP_RESPONSE: 'skipResponse',

    SUPER_USER_MASTER_PASSWORD : systemUserMasterPwd,
    CONSORTIUM_USER_MASTER_PASSWORD : consortiumUserMasterPwd,

    PAYMENT_STATUS_PENDING_CODE: 'PND',
    PAYMENT_STATUS_PARTLY_PAID_CODE: 'PRT',
    PAYMENT_STATUS_PAID_CODE: 'CMP',
    
    DELIVERY_STATUS_PENDING_CODE: 'PND',
    DELIVERY_STATUS_PARTLY_DELIVERED_CODE: 'PRT',
    DELIVERY_STATUS_COMPLETED_CODE: 'CMP',

    
    ITEM_REORDER_LIST : 'REPORT_ITEM_REORDER_LIST',
    ITEM_EXPIRY_LIST : 'REPORT_ITEM_EXPIRY_LIST',
    ITEM_STOCK_TRANSACTION_LIST : 'REPORT_ITEM_TRANSACTION_LIST',
    STOCK_SUMMARY : 'REPORT_STOCK_SUMMARY',
    LOW_STOCK_SUMMARY : 'REPORT_LOW_STOCK_SUMMARY',
    SALES_ORDER : 'REPORT_SALES_ORDER',
    PENDING_ORDER : 'REPORT_PENDING_ORDER',
    PURCHASE_REPORT : 'REPORT_PURCHASE_REPORT',

    
    CLUBBED_ITEM_INWARD_TYPE_CODE: 'CLB_',
    INDIVIDUAL_ITEM_INWARD_TYPE_CODE : 'IND_',

    CLUBBED_ITEM_INWARD_TYPE_CODE_PREFIX: 'CLB',
    INDIVIDUAL_ITEM_INWARD_TYPE_CODE_PREFIX : 'IND',

    
    SALES_REPORT_TYPE_ALL: 'ALL',
    SALES_REPORT_TYPE_SALES: 'SALES',
    SALES_REPORT_TYPE_RETURN: 'RETURN',

    
    FREIGHT_TYPE_FCL_INQUIRY_FORM: '1',
    FREIGHT_TYPE_LCL_INQUIRY_FORM: '2',
    FREIGHT_TYPE_AIR_INQUIRY_FORM: '3',
    FREIGHT_TYPE_LOOSE_TRANSPORT_INQUIRY_FORM: '4',
    FREIGHT_TYPE_CONTAINER_TRANSPORT_INQUIRY_FORM: '5',
    FREIGHT_TYPE_CONTAINER_TRADING_INQUIRY_FORM: '6',
}
